name: Setup Tarantool Test Environment
description: 'Sets up Tarantool and tt'

inputs:
  tarantool-version:
    description: 'Tarantool version to install'
    required: true
    default: '2.11'

runs:
  using: "composite"
  steps:
    - name: setup tarantool
      uses: tarantool/setup-tarantool@v3
      with:
        tarantool-version: ${{ inputs.tarantool-version }}
    - name: add tarantool/modules repo
      shell: bash
      run: |
        os=$(. /etc/os-release && echo $ID)
        dist=$(. /etc/os-release && echo $VERSION_CODENAME)
        curl -L "https://download.tarantool.org/tarantool/modules/gpgkey" | sudo apt-key add -
        apt_source_path="/etc/apt/sources.list.d/tarantool.list"
        echo "deb https://download.tarantool.org/tarantool/modules/${os}/ ${dist} main" | sudo tee ${apt_source_path}
    - name: install tt
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y tt
