name: Setup Tarantool Test Environment
description: 'Sets up Tarantool and dependencies for testing'

inputs:
  tarantool-version:
    description: 'Tarantool version to install'
    required: true

runs:
  using: "composite"
  steps:
    - name: setup tarantool
      uses: ./.github/actions/setup-tarantool
      with:
        tarantool-version: ${{ inputs.tarantool-version }}
    - name: install luacov-coveralls 0.2.3
      shell: bash
      run: tt rocks install --server https://luarocks.org luacov-coveralls 0.2.3
    - name: install luacov-console 1.2.0
      shell: bash
      run: tt rocks --server http://moonlibs.github.io/rocks install luacov-console 1.2.0
    - name: setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: 5.18.4
    - name: install TAP::Harness
      shell: bash
      run: |
        cpanm -v
        cpanm --notest TAP::Harness
