name: Linting with luacheck

on:
  - push
  - pull_request

jobs:
  run-luacheck-linter:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - uses: tarantool/setup-tarantool@v3
      with:
        tarantool-version: '2.11.2'
    - name: install tt
      run: sudo apt-get -y install tt
    - name: install tarantool/luacheck and execute it
      run: tt rocks install luacheck && .rocks/bin/luacheck .
