name: Linting with luacheck

on:
  - push
  - pull_request

jobs:
  run-luacheck-linter:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-tarantool
      with:
        tarantool-version: '2.11'
    - name: install tarantool/luacheck and execute it
      run: tt rocks install luacheck && .rocks/bin/luacheck .
